server:
  port: 8002
spring:
  application:
    name: user-service-provider
  cloud:
    nacos:
      discovery:
        server-addr: www.mynacos.com:8848
        ip: www.mylocalhost.com
dubbo:
  protocol:
    name: dubbo
    port: 20881
  registry:
    #将dubbo服务挂在到Springcloud，本案例中就是读取nacos中的服务
    address: spring-cloud://localhost
  cloud:
    #订阅的服务
    subscribed-services: user-service-consumer
  consumer:
    #订阅的客户端不检查，dubbo在服务启动后，回去检查调用的Reference接口，检查失败，会导致启动不成功
    check: false
