server:
  port: 8008
spring:
  application:
    name: user-service-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #ip: 192.168.106.77
dubbo:
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: spring-cloud://localhost
  cloud:
    #
    subscribed-services: user-service-consumer

