server:
  port: 8003
spring:
  application:
    name: user-service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.106.92:8848
        ip: 192.168.106.77
dubbo:
  cloud:
    #订阅的服务
    subscribed-services: user-service-provider
  protocol:
    port: 20882
    name: dubbo
  registry:
      #将dubbo服务挂在到Springcloud，本案例中就是读取nacos中的服务
      address: spring-cloud://localhost
  consumer:
    #订阅的客户端不检查，dubbo在服务启动后，回去检查调用的Reference接口，检查失败，会导致启动不成功
    check: false
