server:
  port: 8000
spring:
  application:
    name: user-service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #ip: 192.168.106.77
dubbo:
  cloud:
    subscribed-services: user-service-provider
  protocol:
    port: 20882
    name: dubbo
  registry:
      address: spring-cloud://localhost
